# roles/proxmox/vm/defaults/main.yaml
---

# @var deploy_vm:description: >
# If the VM needs to be deployed.
# @end
deploy_vm: false

# @var destroy_vm:description: >
# If VM should be removed/destroyed. This is done before VM is deployed.
# @end
destroy_vm: false

# @var vm_ram_mb:description: >
# Size of the VM memory in MB.
# @end
vm_ram_mb: 2048

# @var vm_root_size:description: >
# The size of the VM root filesystem.
# @end
vm_root_size: 3G

# @var vm_vcpus:description: >
# Number of virtual CPUs to allocate to the VM.
# @end
vm_vcpus: 2

proxmox_vm_template: ubuntu-jammy-cloudinit-template
proxmox_vm_storage: local-lvm

vm_net_ip: "{{ ansible_host }}"
vm_net_mask: 24
vm_net_gateway: ''
