# playbooks/deploy.yaml
---

- hosts: virtual_machines
  gather_facts: false
  become: true
  vars:
    deploy_vm: true
    destroy_vm: false
  roles:
    - role: libvirt

- hosts: proxmox_virtual_machines
  gather_facts: false
  become: false
  vars:
    deploy_vm: true
    destroy_vm: false
  roles:
    - role: proxmox/vm
